version: '3.8'

services:
  sed-api:
    image: 754724220380.dkr.ecr.ap-southeast-2.amazonaws.com/watchme-api-behavior-features:latest
    container_name: sed-api
    ports:
      - "127.0.0.1:8004:8004"
    env_file:
      - /home/ubuntu/api_sed_v1/.env
    networks:
      - watchme-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  watchme-network:
    external: true