version: '3.8'

services:
  watchme-web:
    image: 754724220380.dkr.ecr.ap-southeast-2.amazonaws.com/watchme-web:latest
    container_name: watchme-web-prod
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - /home/ubuntu/watchme-docker/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - /home/ubuntu/watchme-docker/data_accounts:/app/data_accounts
      - /home/ubuntu/watchme-docker/avatars:/app/public/avatars
    networks:
      - watchme-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  watchme-network:
    external: true