version: '3.8'

# =============================================================================
# WatchMe Infrastructure Layer
# =============================================================================
# このファイルは、全サービスが共有するインフラストラクチャリソース
# （ネットワーク、ボリューム等）を定義・管理します。
#
# 使用方法:
#   初回セットアップ: docker-compose -f docker-compose.infra.yml up -d
#   削除: docker-compose -f docker-compose.infra.yml down
#
# 注意: このファイルは全サービスの起動前に実行する必要があります
# =============================================================================

networks:
  # メインの共有ネットワーク
  watchme-network:
    name: watchme-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
    labels:
      created_by: "infrastructure"
      managed_by: "watchme-server-configs"
      version: "1.0"
      description: "Main network for all WatchMe microservices"
      created_at: "2025-08-28"

# 将来的な共有ボリューム定義用（必要に応じて追加）
volumes:
  # 共有データボリューム（将来の拡張用）
  watchme-shared-data:
    name: watchme-shared-data
    labels:
      created_by: "infrastructure"
      managed_by: "watchme-server-configs"
      description: "Shared data volume for WatchMe services"

# Dockerがこのcomposeファイルを管理用として認識するための設定
# 実際のサービスは定義しないが、ダミーサービスで構成を維持
services:
  infrastructure-placeholder:
    image: alpine:latest
    container_name: watchme-infra-placeholder
    command: echo "Infrastructure initialized"
    restart: "no"
    networks:
      - watchme-network