version: '3.8'

services:
  superb-api:
    image: 754724220380.dkr.ecr.ap-southeast-2.amazonaws.com/watchme-api-superb:latest
    container_name: superb-api
    ports:
      - "127.0.0.1:8018:8018"
    env_file:
      - /home/ubuntu/superb/.env
    networks:
      - watchme-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8018/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1500M
          cpus: '1.0'

networks:
  watchme-network:
    external: true